/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package machiwoco;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.MatcherAssert.assertThat; 
import static org.hamcrest.Matchers.is;

class AppTest {
    @Test
    public void testSomething() {
        assertThat(1, is(1));
    }
}
